### PR TITLE
Ex1 Ilay Zeidman and Raz Cohen 

### PR DESCRIPTION
**Pull request by ilayze**
Added the zargo file(ArgoUml project file), xmi, and png file(picture) of the online store use case diagram.
We have created a folder inside the hw folder for our exercise.

### CODE REVIEW

**Comment by ilayze** [comment]
adding @razco

**Comment by robi-y** [comment]
Nice diagram, please proceed with next parts. Good luck

**Comment by robi-y** [comment]
Thanks

**Comment by ilayze** [comment]
Thanks!

2015-03-26 15:30 GMT+02:00 robi-y notifications@github.com:

**Pull request closed without merging**
