### PR TITLE
Ilay Zeidman Raz cohen Final Fixes

### PR DESCRIPTION
**Pull request by ilayze**
Hi,
Two fixes:

1- We added a summary for stage 4 as you asked.
Link to Project Summary(Stage 4): https://github.com/ilayze/sw-modeling-class/blob/master/hw/Raz_Cohen_Ilay_Zeidman/FinalProject/Project%20Summary.docx

2- We added description to the detailed use case.
Link to detailed use case: https://github.com/ilayze/sw-modeling-class/blob/master/hw/Raz_Cohen_Ilay_Zeidman/Ex1/Detailed%20Use%20case%20-%20Checkout.docx

Thanks,
@razco
@ilayze

### CODE REVIEW

**Comment by robi-y** [comment]
:+1:

**Comment by robi-y** [comment]
fine, I just cherry picked #45483ef for the projects page

**Comment by ilayze** [comment]
Thanks! BTW I saw you didn't change our grade neither in the detailed use case nor in the UML of HW1, even though we fixed both and you said it is good...

Thanks,
@razco
@ilayze

**Comment by robi-y** [comment]
Is there a conversation other that he upper :+1:, anyway I'll raise by 1 point

**Comment by razco** [comment]
There are no other conversions other than the conversations mentioned above. 
Thank you very much!

**Pull request closed without merging**
