### PR TITLE
Ex1-Use Case Diagram

### PR DESCRIPTION
**Pull request by havivha**

### CODE REVIEW

**Comment by robi-y** [comment]
Hi,
I need the image for the use case.
So currently you have one OCL constrain (out of 4)
Please add Einat to the conversation by mentioning her @username
Regards, Reuven

**Comment by robi-y** [comment]
Hi,
I wasn't notified about the PR update, probably because it was without a comment
Nice diagrams!
In the detailed UC, under main scenarion there should be clear numbered steps, e.g.,
1. The buyer selects a product
2. The buyer enters purchase details
...

**Comment by robi-y** [comment]
Also please add Einat

**Comment by havivha** [comment]
trying to add Einat.
@einatsc
#einatsc

**Comment by robi-y** [comment]
Great

**Pull request closed without merging**
