### PR TITLE
home assignment 1

### PR DESCRIPTION
**Pull request by eli-z**
By Eli Zaslavchik

### CODE REVIEW

**Comment by robi-y** [comment]
Sorry, I could not read the diagram, please shoe me at class

**Comment by eli-z** [comment]
some files related to hw 1 added

**Comment by robi-y** [comment]
Please explain what have changed or show me at class

**Comment by eli-z** [comment]
added the rest of hw1 above use case diagram that was added before and never feedbacked

**Comment by robi-y** [comment]
Comments:
UCD: missing system rectangle, not clear the UC for inventory manager
Detailed UC: missing pre-condition
Class Diagram - somewhat weak!

**Pull request closed without merging**
