### PR TITLE
Ex1 Ilay Zeidman Raz Cohen 

### PR DESCRIPTION
**Pull request by ilayze**
This pull request contains the 4 diagrams(also added png file for each diagram). and the detailed use case(word document) we will commit the OCL diagram until tomorrow to this pull request.
add @razco

### CODE REVIEW

**Comment by ilayze** [comment]
added car OCL diagram

**Comment by ilayze** [comment]
יש הרבה שדות שלא מופיעים בתצוגה של הדיאגרמה, אבל רואים אותם אם לוחצים על המחלקות באקליפס(דיאגרמת אוסיאל)

**Comment by robi-y** [comment]
Hello,
Diagrams are good. The class diagram has a redundant method - New operation.
Some comments:
-Activity diagram, decision is used for different scenarios (browse, etc), this is a smell that it is not the right diagram
-Deployment: the nodes should contain installed packages, the links are for describing communication protocols
Still missing: detailed UC (part 2)

**Comment by ilayze** [comment]
You can find the detailed UC (part 2) in the document: Detailed Use case - Checkout.docx
What of the above you want me to fix and recommit?

**Comment by ilayze** [comment]
Hi,
We are working now to fix the activity and deployment diagrams, we will submit it to this pull request when it is done.
Thanks,
Ilay and Raz.

**Comment by ilayze** [comment]
Hi,
Fixes to the deployment and activity diagrams have been done according to your comments.

**Comment by robi-y** [comment]
Deployment diagram is much better now

**Pull request closed without merging**
