### PR TITLE
Starting the final project

### PR DESCRIPTION
**Pull request by natanbr**
adding @oshribm88

### CODE REVIEW

**Comment by robi-y** [comment]
Nice start. Try to find resources concerning the architecture and design of this project.
Link your projects details from the table in course readme (by pull request)
good luck

**Comment by natanbr** [comment]
We changed the wrong page. You wrote "link from the project list on the course wiki".
so we changed the wiki page... (https://github.com/jce-il/sw-modeling-class/wiki)
Although, editing the wiki page didn't required a pull request

Do you mean add the link to master/Projects.md? 
We will fix it,
thank you

**Comment by robi-y** [comment]
Yes, we're not working in the wiki (I disabled it now - by default wikis
have public access)

**Comment by natanbr** [comment]
New Update:
adding ppt,

**Comment by natanbr** [comment]
Second attempt

**Comment by robi-y** [comment]
I've used `git cherry-pick` to take only the modified projects.md file

**Pull request closed without merging**
