### PR TITLE
Ilay Zeidman Raz Cohen PPT submission

### PR DESCRIPTION
**Pull request by ilayze**
Also added the wiki link for the final project stage 2.

### CODE REVIEW

**Comment by ilayze** [comment]
adding @razco

**Comment by ilayze** [comment]
By the way you didn't give us grade on part one, here is the relevant PR: 
https://github.com/jce-il/sw-modeling-class/pull/22

**Comment by robi-y** [comment]
I gave for part 1, but not for part 2, since I didn't get the presentation for review... let's see what to do with it

**Comment by ilayze** [comment]
We thought that you review the repository we've created for the project ...

**Comment by robi-y** [comment]
OK, I was not aware of all the wiki pages you wrote - nice

**Pull request merged**
