### PR TITLE
Update Projects.md

### PR DESCRIPTION
**Pull request by assafwe**
No presentation yet.

### CODE REVIEW

**Comment by robi-y** [comment]
I merged it but for full credit you need to provide a list of resources

**Comment by assafwe** [comment]
Of course, this was just for getting started.

Which resources for examples?

thanks

---

מאת: robi-y notifications@github.com
‏‏נשלח: יום חמישי 14 מאי 2015 09:46
‏‏אל: jce-il/sw-modeling-class
עותק: Assaf Weinrib
‏‏נושא: Re: [sw-modeling-class] Update Projects.md (#23)

I merged it but for full credit you need to provide a list of resources

**Comment by robi-y** [comment]
The source code repo is a good start but try to find other books/papers/blog posts that will help build a modeling view of the project

**Comment by assafwe** [comment]
I'm not familiar with an official post, the main communication within the 'VuFind community' is a mailing list where information is shared, questions rise and answer are given either by end users and mainly by the main developer. I participate this list for almost 2 years already, since I was working on this project for my engineering project (Don't you worry, from a totally different aspect).

In addition there the developer calls meetings for updating NFs, rising issues, etc.   but these are also appear in the site: https://vufind.org/wiki/developers_call
VuFind Documentation: developers_call
A library search portal for academic OPACs.
קרא עוד...https://vufind.org/wiki/developers_call

הסר תצוגה מקדימה
isn't that enough?

Thanks

---

מאת: robi-y notifications@github.com
‏‏נשלח: יום חמישי 14 מאי 2015 10:20
‏‏אל: jce-il/sw-modeling-class
עותק: Assaf Weinrib
‏‏נושא: Re: [sw-modeling-class] Update Projects.md (#23)

The source code repo is a good start but try to find other books/papers/blog posts that will help build a modeling view of the project

**Comment by robi-y** [comment]
OK, add this info to your project repo

**Comment by assafwe** [comment]
Added.
In addition, i'll thank you if you can take a look on my fixed EX1_A, as we discussed during the last lecture.
Thanks!

---

מאת: robi-y notifications@github.com
‏‏נשלח: יום חמישי 14 מאי 2015 10:51
‏‏אל: jce-il/sw-modeling-class
עותק: Assaf Weinrib
‏‏נושא: Re: [sw-modeling-class] Update Projects.md (#23)

OK, add this info to your project repo

**Comment by robi-y** [comment]
Is something left for discussion?

**Comment by assafwe** [comment]
i think that currently no.

Thanks

---

מאת: robi-y notifications@github.com
‏‏נשלח: יום ראשון 17 מאי 2015 10:26
‏‏אל: jce-il/sw-modeling-class
עותק: Assaf Weinrib
‏‏נושא: Re: [sw-modeling-class] Update Projects.md (#23)

Is something left for discussion?

**Pull request merged**
