### PR TITLE
Update HW1.B.detailed use case - place order.docx

### PR DESCRIPTION
**Pull request by avitaler**

### CODE REVIEW

**Comment by avitaler** [comment]
The use case was  too general,  The main scenario should be numbered and detailed from the user prespective,

**Comment by avitaler** [comment]
HW2 - Azure class 
@avitaler & @stash2020

**Comment by robi-y** [comment]
Got part a. :+1:

**Comment by avitaler** [comment]
Add Ex2 part b

**Comment by avitaler** [comment]
Add fix for HW1 B

**Comment by avitaler** [comment]
Your action in required:
add 2 files 
1. ex 2 b : contain  output file 
2. ex1 use case, new file to improve the grades

**Comment by robi-y** [comment]
Got HW2b.
HW1b - Use case - not really in the official format, the idea was to pick **one** use case and detail it with goals, pre-conditions, alternate scenario, etc. +1 point...

**Pull request closed without merging**
