### PR TITLE
Ex1

### PR DESCRIPTION
**Pull request by assafwe**
My ex1
Updated fixed Ex1_A.

### CODE REVIEW

**Comment by robi-y** [comment]
As I told you I could not open the xmi file, please show it to me later.
Nice use case description

**Comment by assafwe** [comment]
Ex1 rest of files.
Thanks!

**Comment by assafwe** [comment]
comment.

**Comment by robi-y** [comment]
Hello...
Some comments:

UC diagram: you can inherit the registered user from the non-registered and thus avoid too many links/arrows

Activity diagram: the decision nodes not used for related actions, this is a smell that maybe it is not the right diagram. Use it for a complicated but distinct process.
The "component diagram" is a actually a deployment diagram, but looks excellent

OCL: only one constrain?

**Comment by assafwe** [comment]
Hi Dr.,
It's a bit weird: When i download the OCL file i see 5 constraints?
UC - Right, splitting it to buyer and seller confused me to think that i can't do the inheritance but actually your right.
Activity diagram - i didn't really understand so if you do not have time now to elaborate i'll try to catch you during/after one of the lectures.

Thanks!

**Comment by assafwe** [comment]
your=>you are

**Comment by robi-y** [comment]
Saw now the OCL expressions at the docx file - fine.
Regards

**Comment by assafwe** [comment]
Thanks.
Is the '3' grade for OCL is after you saw the docx or before?

**Comment by robi-y** [comment]
B

**Comment by assafwe** [comment]
Perhaps now?

**Comment by assafwe** [comment]
Ex-2, part 1 has been submitted (3 submitters).
Thanks

**Comment by assafwe** [comment]
Hi,
We merged EX2-pt2 to the repository.

Thanks and Chag Samech,
Assaf, Lior and Maya

**Comment by robi-y** [comment]
Got it Hag Sameach

**Pull request closed without merging**
