### PR TITLE
Website Log Analysis - HDInsight ex1

### PR DESCRIPTION
**Pull request by razco**
Website Log Analysis - HDInsight ex1
Raz Cohen - razco @razco
Ilay Zeidman - ilayze @ilayze
Haviv Haim-Zada - havivha @havivha
Einat Schaefer - einatsc @einatsc

### CODE REVIEW

**Comment by robi-y** [comment]
Got it, nice @razco @ilayze @havivha @einatsc

**Comment by razco** [comment]
@robi-y Added mapreduce wordcount commands + output

This pull request now includes website log analysis output and the mapreduce wordcount
Raz Cohen - razco @razco
Ilay Zeidman - ilayze @ilayze
Haviv Haim-Zada - havivha @havivha
Einat Schaefer - einatsc @einatsc

**Comment by robi-y** [comment]
Great! @razco @ilayze @havivha @einatsc
Was it worth the effort?

**Comment by havivha** [comment]
in my opinion - SURE!! :)
@razco @ilayze @havivha @einatsc

**Pull request closed without merging**
