### PR TITLE
ex1_1 

### PR DESCRIPTION
**Pull request by tamar-b**
Maor Taieb
Tamar Bash

### CODE REVIEW

**Comment by robi-y** [comment]
Hello,
Diagram is fine, missing arrows to denote main actor for each use case.
"Add to chart" -> "Add to cart"
Please correct
Reuven

**Comment by tamar-b** [comment]
you mean that some association relations seems to to be connected to use case but have no actor?  I made an association between any use case and actor, it's the ArgoUML that made it unclear. Is it better now?
usecasediagram

**Comment by robi-y** [comment]
Hi, 
I meant that sometimes an arrow from an actor to a use-case denotes that this is the **primary** actor - but this is not really enforced or widely accepted use.
there is no need to duplicate lines between a derived actor and the same use cases connected to the "base actor"

**Comment by tamar-b** [comment]
Thank you. Is it ok now?
usecasediagram

**Comment by robi-y** [comment]
Still misspelling for 'cart' but fine, let's move on... goos luck

**Comment by tamar-b** [comment]
parts 2-4

**Comment by robi-y** [comment]
Hello,
Please add Maor to the conversation.
Some comment: use case: sigh up is a common feature so usually it is better to discuss first a UC more related to the core "business". Also the use case should be described from the user perspective, so, e.g., a post-condition like user details added to DB is too implementations and technical oriented.
Other diagrams:
Deployment: usually the protocols used for the links should be named (e.g. http). Here it is pretty obvious except maybe for the link to the database.
Overall, very nice work, R

**Pull request closed without merging**
