### PR TITLE
Update Projects.md

### PR DESCRIPTION
**Pull request by assafwe**
Just renaming Repo --> PPT.
Thanks

### CODE REVIEW

**Comment by assafwe** [comment]
Ex4 is done and pushed.
Thanks for your assistance.

Shabat-Shalom

**Comment by robi-y** [comment]
I don't see a new PR for git-immersion

**Comment by assafwe** [comment]
one that has been forked from JCE, it's local inside assafwe - GIT-Immersion-2.

How can i share it with you?

Thanks

---

מאת: robi-y notifications@github.com
‏‏נשלח: יום ראשון 21 יוני 2015 05:14
‏‏אל: jce-il/sw-modeling-class
עותק: Assaf Weinrib
‏‏נושא: Re: [sw-modeling-class] Update Projects.md (#36)

I don't see a new PR for git-immersion

**Comment by robi-y** [comment]
Where? https://github.com/jce-il/git-immersion/network

**Comment by assafwe** [comment]
Hi,

As i said in the other mail - we opened a new local repository Git-Immersion2 for some reason and i was working on it.

I tried the 'Transfer repository option' to take all its content to the forked one but from some reason it didn't let me do it, don't know why yet.

Any other ideas?

Thanks

---

מאת: robi-y notifications@github.com
‏‏נשלח: יום שלישי 23 יוני 2015 22:07
‏‏אל: jce-il/sw-modeling-class
עותק: Assaf Weinrib
‏‏נושא: Re: [sw-modeling-class] Update Projects.md (#36)

Where? https://github.com/jce-il/git-immersion/network

**Pull request closed without merging**
