### PR TITLE
Ilay Zeidman Raz cohen Final Project Stage 4

### PR DESCRIPTION
**Pull request by ilayze**
Hi,
1- We added the document "Project Summary.docx", please put attention we added a new diagram that wasn't in our presentation a Data Flow Diagram (DFD).
The grade is really important to us so if you can give us comments on the document and maybe to raise our grade at the presentation's modeling section.

2- We fixed the detailed use case you can see it in the document "Detailed Use case - Checkout.docx" (Homework1 UML/OCL) and also we fixed the Activity, Deployment diagrams, we will appreciate if you re-check those and change our grade or tell us if something missing.

Thanks,
@ilayze 
@razco

### CODE REVIEW

**Comment by robi-y** [comment]
I don't see your report, please add a commit with a pointer in Project.md, I'll go over the rest too

**Comment by ilayze** [comment]
Done.
Just for the record the URL of the stage 4 is: https://github.com/ilayze/sw-modeling-class/blob/master/hw/Raz_Cohen_Ilay_Zeidman/FinalProject/Project%20Summary.docx

**Comment by robi-y** [comment]
Thanks, I'll merge it
Nice report
I don't see what the DFD adds, and it does not look to me like one (although I already forgot about it...)
A summary section of what you learned etc could be nice

**Comment by robi-y** [comment]
Use case description sees empty??

**Comment by ilayze** [comment]
We opened a new pull request for these two fixes: https://github.com/jce-il/sw-modeling-class/pull/42

**Pull request closed without merging**
